name: multiview
channels:
  - conda-forge
  - default

dependencies:
  - {{ compiler('c') }}
  - {{ compiler('cxx') }}
  - git
  - cmake>=3.15.5
  - python 3.12.0
  - ilmbase 2.5.5
  - openexr 2.5.5
  - boost 1.82.0
  - boost-cpp 1.82.0
  - curl 8.4.0
  - flann 1.9.2
  - gflags 2.2.2
  - glog 0.6.0
  - gmp 6.3.0
  - giflib 5.2.1
  - libopencv 4.8.1
  - libpng 1.6.39
  - libprotobuf 4.24.4
  - libtiff 4.6.0
  - llvm-openmp 17.0.6
  - mpfr 4.2.1
  - numpy 1.26.2
  - opencv 4.8.1
  - openjpeg 2.5.0
  - protobuf 4.24.4
  - python 3.12.0
  - qhull 2020.2
  - pcl 1.13.1
  - qt-main 5.15.8
  - rapidjson 1.1.0
  - rocksdb 8.5.3
  - suitesparse 5.10.1
  - superlu 5.2.2
  - eigen 3.4.0
  - mesalib
  - tbb 2021.10.0
  - tbb-devel 2021.10.0
  - ceres-solver 2.2.0
  - mysql-libs
  - mysql-common
  - mesa-libgl-cos6-x86_64 # [linux]
  - xorg-libxmu # [linux] 
  - xorg-libice # [linux]
  - xorg-libsm # [linux]
  